/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "hello-world": {
    name: "hello-world",
    description: "A simple Hello World component",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/agora-ui/ui/hello-world.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/hello-world.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  button: {
    name: "button",
    description:
      "A button component built with Radix UI and styled with Tailwind CSS",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/agora-ui/ui/button.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "registry/agora-ui/examples/button-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/button.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  popover: {
    name: "popover",
    description: "A popover component built with Radix UI",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/agora-ui/ui/popover.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/popover.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  command: {
    name: "command",
    description: "A combobox component for searchable dropdowns",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/agora-ui/ui/command.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/command.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "agent-picker": {
    name: "agent-picker",
    description: "A dropdown component to select agents from a list",
    type: "registry:ui",
    registryDependencies: ["button", "popover", "command"],
    files: [
      {
        path: "registry/agora-ui/ui/agent-picker.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "registry/agora-ui/examples/agent-picker-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/agent-picker.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  card: {
    name: "card",
    description: "A composable card component for grouping content",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/agora-ui/ui/card.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "registry/agora-ui/examples/card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/card.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  chip: {
    name: "chip",
    description:
      "A flexible wrapper component with rounded pill-shaped background for grouping controls",
    type: "registry:ui",
    registryDependencies: ["button", "mic-selector"],
    files: [
      {
        path: "registry/agora-ui/ui/chip.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "registry/agora-ui/examples/chip-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/chip.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    description: "A dropdown menu component built with Radix UI",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/agora-ui/ui/dropdown-menu.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/dropdown-menu.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "mic-button": {
    name: "mic-button",
    description:
      "A button component with mic icon and states (idle, inactive, processing, error)",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [
      {
        path: "registry/agora-ui/ui/mic-button.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "registry/agora-ui/examples/mic-button-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/mic-button.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "mic-selector": {
    name: "mic-selector",
    description:
      "A button with dropdown menu for selecting items, with mic icon and states",
    type: "registry:ui",
    registryDependencies: ["button", "dropdown-menu", "mic-button"],
    files: [
      {
        path: "registry/agora-ui/ui/mic-selector.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "registry/agora-ui/examples/mic-selector-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/mic-selector.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "live-waveform": {
    name: "live-waveform",
    description:
      "An animated waveform visualization component with states (idle, processing, error)",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/agora-ui/ui/live-waveform.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "registry/agora-ui/examples/live-waveform-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/live-waveform.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  conversation: {
    name: "conversation",
    description:
      "A scrollable conversation component for displaying user and assistant messages",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [
      {
        path: "registry/agora-ui/ui/conversation.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/conversation.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  message: {
    name: "message",
    description: "Message component for displaying individual chat messages",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/agora-ui/ui/message.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/message.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  response: {
    name: "response",
    description: "Response component for displaying message content text",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/agora-ui/ui/response.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/response.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  avatar: {
    name: "avatar",
    description:
      "A flexible avatar component that displays images, icons, or initials",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/agora-ui/ui/avatar.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "registry/agora-ui/examples/avatar-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/agora-ui/ui/avatar.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "conversation-demo": {
    name: "conversation-demo",
    description:
      "A complete conversation component demo with streaming messages",
    type: "registry:ui",
    registryDependencies: ["conversation", "message", "response", "avatar"],
    files: [
      {
        path: "registry/agora-ui/examples/conversation-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/agora-ui/examples/conversation-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
}
